name: Scheduled Match Data Update

on:
  schedule:
    # 매일 자정(UTC 기준)에 실행. 한국 시간으로는 오전 9시
    - cron: '0 0 * * *'

jobs:
  update-match-data:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger match update endpoint
        run: |
          curl -X GET "https://lck-match.onrender.com/api/update-matches"